<?php

use Illuminate\Database\Seeder;

class ParroquiasTableSeeder extends Seeder {

  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    DB::statement("INSERT INTO parroquias
      (id, municipio_id, descripcion, created_by, updated_by, created_at, updated_at)
      VALUES
      (1, 1, 'Altagracia', 1, 1, current_timestamp, current_timestamp),
      (2, 1, 'Antímano', 1, 1, current_timestamp, current_timestamp),
      (3, 1, 'Caricuao', 1, 1, current_timestamp, current_timestamp),
      (4, 1, 'Catedral', 1, 1, current_timestamp, current_timestamp),
      (5, 1, 'Coche', 1, 1, current_timestamp, current_timestamp),
      (6, 1, 'El Junquito', 1, 1, current_timestamp, current_timestamp),
      (7, 1, 'El paraíso', 1, 1, current_timestamp, current_timestamp),
      (8, 1, 'El Recreo', 1, 1, current_timestamp, current_timestamp),
      (9, 1, 'El Valle', 1, 1, current_timestamp, current_timestamp),
      (10, 1, 'La Candelaria', 1, 1, current_timestamp, current_timestamp),
      (11, 1, 'La Pastora', 1, 1, current_timestamp, current_timestamp),
      (12, 1, 'La Vega', 1, 1, current_timestamp, current_timestamp),
      (13, 1, 'Macarao', 1, 1, current_timestamp, current_timestamp),
      (14, 1, 'San Agustín', 1, 1, current_timestamp, current_timestamp),
      (15, 1, 'San Bernardino', 1, 1, current_timestamp, current_timestamp),
      (16, 1, 'San José', 1, 1, current_timestamp, current_timestamp),
      (17, 1, 'San Juan', 1, 1, current_timestamp, current_timestamp),
      (18, 1, 'Santa Rosalia', 1, 1, current_timestamp, current_timestamp),
      (19, 1, 'Santa Teresa', 1, 1, current_timestamp, current_timestamp),
      (20, 1, 'Sucre', 1, 1, current_timestamp, current_timestamp),
      (21, 1, '23 de enero', 1, 1, current_timestamp, current_timestamp),
      (22, 1, 'San Pedro', 1, 1, current_timestamp, current_timestamp),
      (23, 2, 'El Cafetal', 1, 1, current_timestamp, current_timestamp),
      (24, 2, 'Las minas de Baruta', 1, 1, current_timestamp, current_timestamp),
      (25, 2, 'Nuestra Señora del Rosario', 1, 1, current_timestamp, current_timestamp),
      (26, 3, 'Chacao', 1, 1, current_timestamp, current_timestamp),
      (27, 4, 'Petare', 1, 1, current_timestamp, current_timestamp),
      (28, 4, 'Leoncio Martinez', 1, 1, current_timestamp, current_timestamp),
      (29, 4, 'La Dolorita', 1, 1, current_timestamp, current_timestamp),
      (30, 4, 'Caucaguita', 1, 1, current_timestamp, current_timestamp),
      (31, 4, 'Filas de Mariche', 1, 1, current_timestamp, current_timestamp),
      (32, 6, 'Araguita', 1, 1, current_timestamp, current_timestamp),
      (33, 6, 'Arevalo Gonzalez', 1, 1, current_timestamp, current_timestamp),
      (34, 6, 'Capaya', 1, 1, current_timestamp, current_timestamp),
      (35, 6, 'Caucagua', 1, 1, current_timestamp, current_timestamp),
      (36, 6, 'El Cafe', 1, 1, current_timestamp, current_timestamp),
      (37, 6, 'Marizapa', 1, 1, current_timestamp, current_timestamp),
      (38, 6, 'Panaquire', 1, 1, current_timestamp, current_timestamp),
      (39, 6, 'Ribas', 1, 1, current_timestamp, current_timestamp),
      (40, 7, 'Cumbo', 1, 1, current_timestamp, current_timestamp),
      (41, 7, 'San Jose Barlovento', 1, 1, current_timestamp, current_timestamp),
      (42, 8, 'Curiepe', 1, 1, current_timestamp, current_timestamp),
      (43, 8, 'Higuerote', 1, 1, current_timestamp, current_timestamp),
      (44, 8, 'Tacarigua', 1, 1, current_timestamp, current_timestamp),
      (45, 9, 'Mamporal', 1, 1, current_timestamp, current_timestamp),
      (46, 10, 'Carrizal', 1, 1, current_timestamp, current_timestamp),
      (47, 11, 'Charallave', 1, 1, current_timestamp, current_timestamp),
      (48, 11, 'Las Brisas', 1, 1, current_timestamp, current_timestamp),
      (49, 12, 'Altagracia de la M', 1, 1, current_timestamp, current_timestamp),
      (50, 12, 'Cecilio Acosta', 1, 1, current_timestamp, current_timestamp),
      (51, 12, 'El Jarillo', 1, 1, current_timestamp, current_timestamp),
      (52, 12, 'Los Teques', 1, 1, current_timestamp, current_timestamp),
      (53, 12, 'Paracotos', 1, 1, current_timestamp, current_timestamp),
      (54, 12, 'San Pedro', 1, 1, current_timestamp, current_timestamp),
      (55, 12, 'Tacata', 1, 1, current_timestamp, current_timestamp),
      (56, 13, 'El Cartanal', 1, 1, current_timestamp, current_timestamp),
      (57, 13, 'Sta Teresa del Tuy', 1, 1, current_timestamp, current_timestamp),
      (58, 14, 'La Democracia', 1, 1, current_timestamp, current_timestamp),
      (59, 14, 'Ocumare del Tuy', 1, 1, current_timestamp, current_timestamp),
      (60, 14, 'Santa Barbara', 1, 1, current_timestamp, current_timestamp),
      (61, 15, 'San Antonio de los altos', 1, 1, current_timestamp, current_timestamp),
      (62, 16, 'El Guapo', 1, 1, current_timestamp, current_timestamp),
      (63, 16, 'Paparo', 1, 1, current_timestamp, current_timestamp),
      (64, 16, 'Tacarigua de la laguna', 1, 1, current_timestamp, current_timestamp),
      (65, 16, 'Rio Chico', 1, 1, current_timestamp, current_timestamp),
      (66, 16, 'San Fernardo del Guapo', 1, 1, current_timestamp, current_timestamp),
      (67, 17, 'Santa Lucia', 1, 1, current_timestamp, current_timestamp),
      (68, 18, 'Cupira', 1, 1, current_timestamp, current_timestamp),
      (69, 18, 'Machurucuto', 1, 1, current_timestamp, current_timestamp),
      (70, 19, 'Guarenas', 1, 1, current_timestamp, current_timestamp),
      (71, 20, 'San Francisco de Yare', 1, 1, current_timestamp, current_timestamp),
      (72, 20, 'San Antonio de Yare', 1, 1, current_timestamp, current_timestamp),
      (73, 21, 'Cua', 1, 1, current_timestamp, current_timestamp),
      (74, 21, 'Nueva Cua', 1, 1, current_timestamp, current_timestamp),
      (75, 22, 'Bolivar', 1, 1, current_timestamp, current_timestamp),
      (76, 22, 'Guatire', 1, 1, current_timestamp, current_timestamp),
      (77, 23, 'Caraballeda', 1, 1, current_timestamp, current_timestamp),
      (78, 23, 'Carayaca', 1, 1, current_timestamp, current_timestamp),
      (79, 23, 'Carlos Soublette', 1, 1, current_timestamp, current_timestamp),
      (80, 23, 'Caruao', 1, 1, current_timestamp, current_timestamp),
      (81, 23, 'Catia la mar', 1, 1, current_timestamp, current_timestamp),
      (82, 23, 'El Junko', 1, 1, current_timestamp, current_timestamp),
      (83, 23, 'La Guaira', 1, 1, current_timestamp, current_timestamp),
      (84, 23, 'Macuto', 1, 1, current_timestamp, current_timestamp),
      (85, 23, 'Maiquetia', 1, 1, current_timestamp, current_timestamp),
      (86, 23, 'Naiguata', 1, 1, current_timestamp, current_timestamp),
      (87, 23, 'Urimare', 1, 1, current_timestamp, current_timestamp),
      (88, 24, 'Camaguan', 1, 1, current_timestamp, current_timestamp),
      (89, 24, 'Puerto Miranda', 1, 1, current_timestamp, current_timestamp),
      (90, 24, 'Uverito', 1, 1, current_timestamp, current_timestamp),
      (91, 25, 'Chaguaramas', 1, 1, current_timestamp, current_timestamp),
      (92, 26, 'El Socorro', 1, 1, current_timestamp, current_timestamp),
      (93, 27, 'Calabozo', 1, 1, current_timestamp, current_timestamp),
      (94, 27, 'El Calvario', 1, 1, current_timestamp, current_timestamp),
      (95, 27, 'El rastro', 1, 1, current_timestamp, current_timestamp),
      (96, 27, 'Guardatinajas', 1, 1, current_timestamp, current_timestamp),
      (97, 28, 'San Rafael de Laya', 1, 1, current_timestamp, current_timestamp),
      (98, 28, 'Tucupido', 1, 1, current_timestamp, current_timestamp),
      (99, 29, 'Altagracia de Orituco', 1, 1, current_timestamp, current_timestamp),
      (100, 29, 'Lezama', 1, 1, current_timestamp, current_timestamp),
      (101, 29, 'Libertad de Orituco', 1, 1, current_timestamp, current_timestamp),
      (102, 29, 'Paso real de Macaira', 1, 1, current_timestamp, current_timestamp),
      (103, 29, 'San Fco de Macaira', 1, 1, current_timestamp, current_timestamp),
      (104, 29, 'San Rafael de Orituco', 1, 1, current_timestamp, current_timestamp),
      (105, 29, 'Soublette', 1, 1, current_timestamp, current_timestamp),
      (106, 30, 'Cantagallo', 1, 1, current_timestamp, current_timestamp),
      (107, 30, 'Parapara', 1, 1, current_timestamp, current_timestamp),
      (108, 30, 'San Juan de los Morros', 1, 1, current_timestamp, current_timestamp),
      (109, 31, 'El Sombrero', 1, 1, current_timestamp, current_timestamp),
      (110, 31, 'Sosa', 1, 1, current_timestamp, current_timestamp),
      (111, 32, 'Cabruta', 1, 1, current_timestamp, current_timestamp),
      (112, 32, 'Las Mercedes', 1, 1, current_timestamp, current_timestamp),
      (113, 32, 'Santa Rita de Manapire', 1, 1, current_timestamp, current_timestamp),
      (114, 33, 'Espino', 1, 1, current_timestamp, current_timestamp),
      (115, 33, 'Valle de la Pascua', 1, 1, current_timestamp, current_timestamp),
      (116, 34, 'Ortiz', 1, 1, current_timestamp, current_timestamp),
      (117, 34, 'Sn Fco de Tiznados', 1, 1, current_timestamp, current_timestamp),
      (118, 34, 'San Jose de Tiznados', 1, 1, current_timestamp, current_timestamp),
      (119, 34, 'Sn Lorenzo de tiznados', 1, 1, current_timestamp, current_timestamp),
      (120, 35, 'San Jose de Unare', 1, 1, current_timestamp, current_timestamp),
      (121, 35, 'Zaraza', 1, 1, current_timestamp, current_timestamp),
      (122, 36, 'Cazorla', 1, 1, current_timestamp, current_timestamp),
      (123, 36, 'Guayabal', 1, 1, current_timestamp, current_timestamp),
      (124, 37, 'San Jose de Guaribe', 1, 1, current_timestamp, current_timestamp),
      (125, 38, 'Altamira', 1, 1, current_timestamp, current_timestamp),
      (126, 38, 'Santa Maria de Ipire', 1, 1, current_timestamp, current_timestamp),
      (127, 39, 'San Mateo', 1, 1, current_timestamp, current_timestamp),
      (128, 41, 'Carmen de Cura', 1, 1, current_timestamp, current_timestamp),
      (129, 41, 'Camatagua', 1, 1, current_timestamp, current_timestamp),
      (130, 42, 'Santa Rita', 1, 1, current_timestamp, current_timestamp),
      (131, 42, 'Francisco de Miranda', 1, 1, current_timestamp, current_timestamp),
      (132, 42, 'Mons Feliciano', 1, 1, current_timestamp, current_timestamp),
      (133, 43, 'Andres Eloy Blanco', 1, 1, current_timestamp, current_timestamp),
      (134, 43, 'Choroni', 1, 1, current_timestamp, current_timestamp),
      (135, 43, 'Joaquin Crespo', 1, 1, current_timestamp, current_timestamp),
      (136, 43, 'Jose Casanova Godoy', 1, 1, current_timestamp, current_timestamp),
      (137, 43, 'Las Delicias', 1, 1, current_timestamp, current_timestamp),
      (138, 43, 'Los Tacariguas', 1, 1, current_timestamp, current_timestamp),
      (139, 43, 'Madre Ma de San Jose', 1, 1, current_timestamp, current_timestamp),
      (140, 43, 'Pedro Jose Ovalies', 1, 1, current_timestamp, current_timestamp),
      (141, 44, 'Santa Cruz', 1, 1, current_timestamp, current_timestamp),
      (142, 45, 'Castor Nieves Rios', 1, 1, current_timestamp, current_timestamp),
      (143, 45, 'La Victoria', 1, 1, current_timestamp, current_timestamp),
      (144, 45, 'Las Guacamayas', 1, 1, current_timestamp, current_timestamp),
      (145, 45, 'Pao de Zarate', 1, 1, current_timestamp, current_timestamp),
      (146, 45, 'Zuata', 1, 1, current_timestamp, current_timestamp),
      (147, 46, 'El Consejo', 1, 1, current_timestamp, current_timestamp),
      (148, 47, 'Palo Negro', 1, 1, current_timestamp, current_timestamp),
      (149, 47, 'Martin de Porres', 1, 1, current_timestamp, current_timestamp),
      (150, 48, 'Ca de Azucar', 1, 1, current_timestamp, current_timestamp),
      (151, 48, 'El Limon', 1, 1, current_timestamp, current_timestamp),
      (152, 49, 'Ocumare de la costa', 1, 1, current_timestamp, current_timestamp),
      (153, 50, 'San Casimiro', 1, 1, current_timestamp, current_timestamp),
      (154, 50, 'Guiripa', 1, 1, current_timestamp, current_timestamp),
      (155, 50, 'Ollas de Caramacate', 1, 1, current_timestamp, current_timestamp),
      (156, 50, 'Valle Morin', 1, 1, current_timestamp, current_timestamp),
      (157, 51, 'San Sebastian', 1, 1, current_timestamp, current_timestamp),
      (158, 52, 'Alfredo Pacheco', 1, 1, current_timestamp, current_timestamp),
      (159, 52, 'Arevalo Aponte', 1, 1, current_timestamp, current_timestamp),
      (160, 52, 'Chuao', 1, 1, current_timestamp, current_timestamp),
      (161, 52, 'Turumero', 1, 1, current_timestamp, current_timestamp),
      (162, 52, 'Saman de Guere', 1, 1, current_timestamp, current_timestamp),
      (163, 53, 'Las Tejerias', 1, 1, current_timestamp, current_timestamp),
      (164, 53, 'Tiara', 1, 1, current_timestamp, current_timestamp),
      (165, 54, 'Bella Vista', 1, 1, current_timestamp, current_timestamp),
      (166, 54, 'Cagua', 1, 1, current_timestamp, current_timestamp),
      (167, 55, 'Colonia Tovar', 1, 1, current_timestamp, current_timestamp),
      (168, 56, 'Barbacoas', 1, 1, current_timestamp, current_timestamp),
      (169, 56, 'Las Peñitas', 1, 1, current_timestamp, current_timestamp),
      (170, 56, 'San Francisco de Cara', 1, 1, current_timestamp, current_timestamp),
      (171, 56, 'Taguay', 1, 1, current_timestamp, current_timestamp),
      (172, 57, 'Augusto Mijares', 1, 1, current_timestamp, current_timestamp),
      (173, 57, 'Villa de cura', 1, 1, current_timestamp, current_timestamp),
      (174, 57, 'Magdaleno', 1, 1, current_timestamp, current_timestamp),
      (175, 57, 'Sam Francisco de Asis', 1, 1, current_timestamp, current_timestamp),
      (176, 57, 'Valles de Tucutunemo', 1, 1, current_timestamp, current_timestamp),
      (177, 58, 'Bejuma', 1, 1, current_timestamp, current_timestamp),
      (178, 58, 'Canoabo', 1, 1, current_timestamp, current_timestamp),
      (179, 58, 'Simon Bolivar', 1, 1, current_timestamp, current_timestamp),
      (180, 59, 'Belen', 1, 1, current_timestamp, current_timestamp),
      (181, 59, 'Guigue', 1, 1, current_timestamp, current_timestamp),
      (182, 59, 'Tacarigua', 1, 1, current_timestamp, current_timestamp),
      (183, 60, 'Agua Caliente', 1, 1, current_timestamp, current_timestamp),
      (184, 60, 'Mariara', 1, 1, current_timestamp, current_timestamp),
      (185, 61, 'Ciudad Alianza', 1, 1, current_timestamp, current_timestamp),
      (186, 61, 'Guacara', 1, 1, current_timestamp, current_timestamp),
      (187, 61, 'Yagua', 1, 1, current_timestamp, current_timestamp),
      (188, 62, 'Moron', 1, 1, current_timestamp, current_timestamp),
      (189, 62, 'Urama', 1, 1, current_timestamp, current_timestamp),
      (190, 63, 'Independencia', 1, 1, current_timestamp, current_timestamp),
      (191, 63, 'Tocuyito', 1, 1, current_timestamp, current_timestamp),
      (192, 64, 'Los Guayos', 1, 1, current_timestamp, current_timestamp),
      (193, 65, 'Miranda', 1, 1, current_timestamp, current_timestamp),
      (194, 66, 'Montalban', 1, 1, current_timestamp, current_timestamp),
      (195, 67, 'Naguanagua', 1, 1, current_timestamp, current_timestamp),
      (196, 68, 'Bartolome Salom', 1, 1, current_timestamp, current_timestamp),
      (197, 68, 'Borburata', 1, 1, current_timestamp, current_timestamp),
      (198, 68, 'Democracia', 1, 1, current_timestamp, current_timestamp),
      (199, 68, 'Fraternidad', 1, 1, current_timestamp, current_timestamp),
      (200, 68, 'Goaigoaza', 1, 1, current_timestamp, current_timestamp),
      (201, 68, 'Juan Jose Flores', 1, 1, current_timestamp, current_timestamp),
      (202, 68, 'Patanemo', 1, 1, current_timestamp, current_timestamp),
      (203, 68, 'Union', 1, 1, current_timestamp, current_timestamp),
      (204, 69, 'San Diego', 1, 1, current_timestamp, current_timestamp),
      (205, 70, 'San Joaquin', 1, 1, current_timestamp, current_timestamp),
      (206, 71, 'Candelaria', 1, 1, current_timestamp, current_timestamp),
      (207, 71, 'Catedral', 1, 1, current_timestamp, current_timestamp),
      (208, 71, 'El Socorro', 1, 1, current_timestamp, current_timestamp),
      (209, 71, 'Miguel Peña', 1, 1, current_timestamp, current_timestamp),
      (210, 71, 'Negro Primero', 1, 1, current_timestamp, current_timestamp),
      (211, 71, 'Rafael Urdaneta', 1, 1, current_timestamp, current_timestamp),
      (212, 71, 'San Bias', 1, 1, current_timestamp, current_timestamp),
      (213, 71, 'San Jose', 1, 1, current_timestamp, current_timestamp),
      (214, 71, 'Santa Rosa', 1, 1, current_timestamp, current_timestamp),
      (215, 5, 'El Hatillo', 1, 1, current_timestamp, current_timestamp),
      (216, 93, 'Alto Orinoco La Esmeralda', 1, 1, current_timestamp, current_timestamp),
      (217, 93, 'Huachamacare Acanaña', 1, 1, current_timestamp, current_timestamp),
      (218, 93, 'Marawaka Toky Shamanaña', 1, 1, current_timestamp, current_timestamp),
      (219, 93, 'Mavaka Mavaka', 1, 1, current_timestamp, current_timestamp),
      (220, 93, 'Sierra Parima Parimabé', 1, 1, current_timestamp, current_timestamp),
      (221, 94, 'Ucata Laja Lisa', 1, 1, current_timestamp, current_timestamp),
      (222, 94, 'Yapacana Macuruco', 1, 1, current_timestamp, current_timestamp),
      (223, 94, 'Caname Guarinuma', 1, 1, current_timestamp, current_timestamp),
      (224, 95, 'Fernando Girón Tovar Puerto Ayacucho', 1, 1, current_timestamp, current_timestamp),
      (225, 95, 'Luis Alberto Gómez Puerto Ayacucho', 1, 1, current_timestamp, current_timestamp),
      (226, 95, 'Pahueña Limón de Parhueña', 1, 1, current_timestamp, current_timestamp),
      (227, 95, 'Platanillal Platanillal', 1, 1, current_timestamp, current_timestamp),
      (228, 96, 'Samariapo Samariapo', 1, 1, current_timestamp, current_timestamp),
      (229, 96, 'Sipapo Pendare', 1, 1, current_timestamp, current_timestamp),
      (230, 96, 'Munduapo Munduapo', 1, 1, current_timestamp, current_timestamp),
      (231, 96, 'Guayapo San Pedro del Orinoco', 1, 1, current_timestamp, current_timestamp),
      (232, 97, 'Alto Ventuari Cacurí', 1, 1, current_timestamp, current_timestamp),
      (233, 97, 'Medio Ventuari Manami', 1, 1, current_timestamp, current_timestamp),
      (234, 97, 'Ventuari Marueta', 1, 1, current_timestamp, current_timestamp),
      (235, 98, 'Victorino', 1, 1, current_timestamp, current_timestamp),
      (236, 98, 'Comunidad', 1, 1, current_timestamp, current_timestamp),
      (237, 99, 'Casiquiare Curimacare', 1, 1, current_timestamp, current_timestamp),
      (238, 99, 'Cucuy', 1, 1, current_timestamp, current_timestamp),
      (239, 99, 'Casiquiare Curimacare', 1, 1, current_timestamp, current_timestamp),
      (240, 99, 'Solano Solano', 1, 1, current_timestamp, current_timestamp),
      (241, 72, 'Anaco', 1, 1, current_timestamp, current_timestamp),
      (242, 72, 'San Joaquín', 1, 1, current_timestamp, current_timestamp),
      (243, 73, 'Cachipo', 1, 1, current_timestamp, current_timestamp),
      (244, 73, 'Aragua de Barcelona', 1, 1, current_timestamp, current_timestamp),
      (245, 78, 'Lechería', 1, 1, current_timestamp, current_timestamp),
      (246, 78, 'El Morro', 1, 1, current_timestamp, current_timestamp),
      (247, 87, 'Puerto Píritu', 1, 1, current_timestamp, current_timestamp),
      (248, 87, 'San Miguel', 1, 1, current_timestamp, current_timestamp),
      (249, 87, 'Sucre', 1, 1, current_timestamp, current_timestamp),
      (250, 77, 'Valle de Guanape', 1, 1, current_timestamp, current_timestamp),
      (251, 77, 'Santa Bárbara', 1, 1, current_timestamp, current_timestamp),
      (252, 85, 'Atapirire', 1, 1, current_timestamp, current_timestamp),
      (253, 85, 'Boca del Pao', 1, 1, current_timestamp, current_timestamp),
      (254, 85, 'El Pao', 1, 1, current_timestamp, current_timestamp),
      (255, 85, 'Pariaguán', 1, 1, current_timestamp, current_timestamp),
      (256, 81, 'Guanta', 1, 1, current_timestamp, current_timestamp),
      (257, 81, 'Chorrerón', 1, 1, current_timestamp, current_timestamp),
      (258, 82, 'Mamo', 1, 1, current_timestamp, current_timestamp),
      (259, 82, 'Soledad', 1, 1, current_timestamp, current_timestamp),
      (260, 86, 'Mapire', 1, 1, current_timestamp, current_timestamp),
      (261, 86, 'Piar', 1, 1, current_timestamp, current_timestamp),
      (262, 86, 'Santa Clara', 1, 1, current_timestamp, current_timestamp),
      (263, 86, 'San Diego de Cabrutica', 1, 1, current_timestamp, current_timestamp),
      (264, 86, 'Uverito', 1, 1, current_timestamp, current_timestamp),
      (265, 86, 'Zuata', 1, 1, current_timestamp, current_timestamp),
      (266, 92, 'Puerto La Cruz', 1, 1, current_timestamp, current_timestamp),
      (267, 92, 'Pozuelos', 1, 1, current_timestamp, current_timestamp),
      (268, 76, 'Onoto', 1, 1, current_timestamp, current_timestamp),
      (269, 76, 'San Pablo', 1, 1, current_timestamp, current_timestamp),
      (270, 83, 'San Mateo', 1, 1, current_timestamp, current_timestamp),
      (271, 83, 'El Carito', 1, 1, current_timestamp, current_timestamp),
      (272, 83, 'Santa Inés', 1, 1, current_timestamp, current_timestamp),
      (273, 83, 'La Romereña', 1, 1, current_timestamp, current_timestamp),
      (274, 75, 'Clarines', 1, 1, current_timestamp, current_timestamp),
      (275, 75, 'Guanape', 1, 1, current_timestamp, current_timestamp),
      (276, 75, 'Sabana de Uchire', 1, 1, current_timestamp, current_timestamp),
      (277, 79, 'Cantaura', 1, 1, current_timestamp, current_timestamp),
      (278, 79, 'Libertador', 1, 1, current_timestamp, current_timestamp),
      (279, 79, 'Santa Rosa', 1, 1, current_timestamp, current_timestamp),
      (280, 79, 'Urica', 1, 1, current_timestamp, current_timestamp),
      (281, 88, 'Píritu', 1, 1, current_timestamp, current_timestamp),
      (282, 88, 'San Francisco', 1, 1, current_timestamp, current_timestamp),
      (283, 80, 'San José de Guanipa', 1, 1, current_timestamp, current_timestamp),
      (284, 89, 'Boca de Uchire', 1, 1, current_timestamp, current_timestamp),
      (285, 89, 'Boca de Chávez', 1, 1, current_timestamp, current_timestamp),
      (286, 90, 'Pueblo Nuevo', 1, 1, current_timestamp, current_timestamp),
      (287, 90, 'Santa Ana', 1, 1, current_timestamp, current_timestamp),
      (288, 74, 'Bergatín', 1, 1, current_timestamp, current_timestamp),
      (289, 74, 'Caigua', 1, 1, current_timestamp, current_timestamp),
      (290, 74, 'El Carmen', 1, 1, current_timestamp, current_timestamp),
      (291, 74, 'El Pilar', 1, 1, current_timestamp, current_timestamp),
      (292, 74, 'Naricual', 1, 1, current_timestamp, current_timestamp),
      (293, 74, 'San Cristóbal', 1, 1, current_timestamp, current_timestamp),
      (294, 91, 'Edmundo Barrios', 1, 1, current_timestamp, current_timestamp),
      (295, 91, 'Miguel Otero Silva', 1, 1, current_timestamp, current_timestamp),
      (296, 84, 'El Chaparro', 1, 1, current_timestamp, current_timestamp),
      (297, 84, 'Tomás Alfaro', 1, 1, current_timestamp, current_timestamp),
      (298, 84, 'Calatrava', 1, 1, current_timestamp, current_timestamp),
      (299, 100, 'Achaguas', 1, 1, current_timestamp, current_timestamp),
      (300, 100, 'Apurito', 1, 1, current_timestamp, current_timestamp),
      (301, 100, 'El Yagual', 1, 1, current_timestamp, current_timestamp),
      (302, 100, 'Guachara', 1, 1, current_timestamp, current_timestamp),
      (303, 100, 'Mucuritas', 1, 1, current_timestamp, current_timestamp),
      (304, 100, 'Queseras del medio', 1, 1, current_timestamp, current_timestamp),
      (305, 101, 'Biruaca', 1, 1, current_timestamp, current_timestamp),
      (306, 102, 'Bruzual', 1, 1, current_timestamp, current_timestamp),
      (307, 102, 'Mantecal', 1, 1, current_timestamp, current_timestamp),
      (308, 102, 'Quintero', 1, 1, current_timestamp, current_timestamp),
      (309, 102, 'Rincón Hondo', 1, 1, current_timestamp, current_timestamp),
      (310, 102, 'San Vicente', 1, 1, current_timestamp, current_timestamp),
      (311, 104, 'San Juan de Payara', 1, 1, current_timestamp, current_timestamp),
      (312, 104, 'Codazzzi', 1, 1, current_timestamp, current_timestamp),
      (313, 104, 'Cunaviche', 1, 1, current_timestamp, current_timestamp),
      (314, 106, 'San Fernando', 1, 1, current_timestamp, current_timestamp),
      (315, 106, 'El Recre0', 1, 1, current_timestamp, current_timestamp),
      (316, 106, 'Peñalver', 1, 1, current_timestamp, current_timestamp),
      (317, 106, 'San Rafael de Atamaica', 1, 1, current_timestamp, current_timestamp),
      (318, 103, 'Guasdualito', 1, 1, current_timestamp, current_timestamp),
      (319, 103, 'Aramendi', 1, 1, current_timestamp, current_timestamp),
      (320, 103, 'El Amparo', 1, 1, current_timestamp, current_timestamp),
      (321, 103, 'San Camilo', 1, 1, current_timestamp, current_timestamp),
      (322, 103, 'Urdaneta', 1, 1, current_timestamp, current_timestamp),
      (323, 105, 'Elorza', 1, 1, current_timestamp, current_timestamp),
      (324, 105, 'La Trinidad', 1, 1, current_timestamp, current_timestamp),
      (325, 107, 'Sabaneta', 1, 1, current_timestamp, current_timestamp),
      (326, 107, 'Juan Antonio Rodríguez Domínguez', 1, 1, current_timestamp, current_timestamp),
      (327, 108, 'El Cantón', 1, 1, current_timestamp, current_timestamp),
      (328, 108, 'Santa Cruz de Guacas', 1, 1, current_timestamp, current_timestamp),
      (329, 108, 'Puerto Vivas', 1, 1, current_timestamp, current_timestamp),
      (330, 109, 'Ticoporo', 1, 1, current_timestamp, current_timestamp),
      (331, 109, 'Nicolás Pulido', 1, 1, current_timestamp, current_timestamp),
      (332, 109, 'Andrés Bello', 1, 1, current_timestamp, current_timestamp),
      (333, 110, 'Arismendi', 1, 1, current_timestamp, current_timestamp),
      (334, 110, 'Guadarrama', 1, 1, current_timestamp, current_timestamp),
      (335, 110, 'La Unión', 1, 1, current_timestamp, current_timestamp),
      (336, 110, 'San Antonio', 1, 1, current_timestamp, current_timestamp),
      (337, 111, 'Barinas', 1, 1, current_timestamp, current_timestamp),
      (338, 111, 'Alberto Arvelo Larriva', 1, 1, current_timestamp, current_timestamp),
      (339, 111, 'San Silvestre', 1, 1, current_timestamp, current_timestamp),
      (340, 111, 'Santa Inés', 1, 1, current_timestamp, current_timestamp),
      (341, 111, 'Santa Lucía', 1, 1, current_timestamp, current_timestamp),
      (342, 111, 'Torunos', 1, 1, current_timestamp, current_timestamp),
      (343, 111, 'El Carmen', 1, 1, current_timestamp, current_timestamp),
      (344, 111, 'Rómulo Betancourt', 1, 1, current_timestamp, current_timestamp),
      (345, 111, 'Corazón de Jesús', 1, 1, current_timestamp, current_timestamp),
      (346, 111, 'Ramón Ignacio', 1, 1, current_timestamp, current_timestamp),
      (347, 111, 'Alto Barinas', 1, 1, current_timestamp, current_timestamp),
      (348, 111, 'Manuel Palacio Fajardo', 1, 1, current_timestamp, current_timestamp),
      (349, 111, 'Juan Antonio Rodríguez Domínguez', 1, 1, current_timestamp, current_timestamp),
      (350, 111, 'Dominga Ortiz de Páez', 1, 1, current_timestamp, current_timestamp),
      (351, 112, 'Barinitas', 1, 1, current_timestamp, current_timestamp),
      (352, 112, 'Altamira de Cáceres', 1, 1, current_timestamp, current_timestamp),
      (353, 112, 'Calderas', 1, 1, current_timestamp, current_timestamp),
      (354, 113, 'Barracas', 1, 1, current_timestamp, current_timestamp),
      (355, 113, 'El Socorro', 1, 1, current_timestamp, current_timestamp),
      (356, 113, 'Mazparrito', 1, 1, current_timestamp, current_timestamp),
      (357, 114, 'Santa Bárbara', 1, 1, current_timestamp, current_timestamp),
      (358, 114, 'Pedro Briceño Méndez', 1, 1, current_timestamp, current_timestamp),
      (359, 114, 'Ramón Ignacio Méndez', 1, 1, current_timestamp, current_timestamp),
      (360, 114, 'José Ignacio del Pumar', 1, 1, current_timestamp, current_timestamp),
      (361, 115, 'Obispos', 1, 1, current_timestamp, current_timestamp),
      (362, 115, 'Los Guasimitos', 1, 1, current_timestamp, current_timestamp),
      (363, 115, 'El Real', 1, 1, current_timestamp, current_timestamp),
      (364, 115, 'La Luz', 1, 1, current_timestamp, current_timestamp),
      (365, 116, 'Ciudad Bolívia', 1, 1, current_timestamp, current_timestamp),
      (366, 116, 'José Ignacio Briceño', 1, 1, current_timestamp, current_timestamp),
      (367, 116, 'José Félix Ribas', 1, 1, current_timestamp, current_timestamp),
      (368, 116, 'Páez', 1, 1, current_timestamp, current_timestamp),
      (369, 117, 'Libertad', 1, 1, current_timestamp, current_timestamp),
      (370, 117, 'Dolores', 1, 1, current_timestamp, current_timestamp),
      (371, 117, 'Santa Rosa', 1, 1, current_timestamp, current_timestamp),
      (372, 117, 'Palacio Fajardo', 1, 1, current_timestamp, current_timestamp),
      (373, 117, 'Simón Rodríguez', 1, 1, current_timestamp, current_timestamp),
      (374, 118, 'Ciudad de Nutrias', 1, 1, current_timestamp, current_timestamp),
      (375, 118, 'El Regalo', 1, 1, current_timestamp, current_timestamp),
      (376, 118, 'Puerto Nutrias', 1, 1, current_timestamp, current_timestamp),
      (377, 118, 'Santa Catalina', 1, 1, current_timestamp, current_timestamp),
      (378, 118, 'Simón Bolívar', 1, 1, current_timestamp, current_timestamp),
      (379, 119, 'Cachamay', 1, 1, current_timestamp, current_timestamp),
      (380, 119, 'Chirica', 1, 1, current_timestamp, current_timestamp),
      (381, 119, 'Dalla Costa', 1, 1, current_timestamp, current_timestamp),
      (382, 119, 'Once de Abril', 1, 1, current_timestamp, current_timestamp),
      (383, 119, 'Simón Bolívar', 1, 1, current_timestamp, current_timestamp),
      (384, 119, 'Unare', 1, 1, current_timestamp, current_timestamp),
      (385, 119, 'Universidad', 1, 1, current_timestamp, current_timestamp),
      (386, 119, 'Vista al Sol', 1, 1, current_timestamp, current_timestamp),
      (387, 119, 'Pozo Verde', 1, 1, current_timestamp, current_timestamp),
      (388, 119, 'Yocoima', 1, 1, current_timestamp, current_timestamp),
      (389, 119, '5 de Julio', 1, 1, current_timestamp, current_timestamp),
      (390, 120, 'Cedeño', 1, 1, current_timestamp, current_timestamp),
      (391, 120, 'Altagracia', 1, 1, current_timestamp, current_timestamp),
      (392, 120, 'Ascensión Farreras', 1, 1, current_timestamp, current_timestamp),
      (393, 120, 'Guaniamo', 1, 1, current_timestamp, current_timestamp),
      (394, 120, 'La Urbana', 1, 1, current_timestamp, current_timestamp),
      (395, 120, 'Pijiguaos', 1, 1, current_timestamp, current_timestamp),
      (396, 121, 'El Callao', 1, 1, current_timestamp, current_timestamp),
      (397, 122, 'Gran Sabana', 1, 1, current_timestamp, current_timestamp),
      (398, 122, 'Ikabarú', 1, 1, current_timestamp, current_timestamp),
      (399, 123, 'Catedral', 1, 1, current_timestamp, current_timestamp),
      (400, 123, 'Zea', 1, 1, current_timestamp, current_timestamp),
      (401, 123, 'Orinoco', 1, 1, current_timestamp, current_timestamp),
      (402, 123, 'José Antonio Páez', 1, 1, current_timestamp, current_timestamp),
      (403, 123, 'Marhuanta', 1, 1, current_timestamp, current_timestamp),
      (404, 123, 'Agua Salada', 1, 1, current_timestamp, current_timestamp),
      (405, 123, 'Vista Hermosa', 1, 1, current_timestamp, current_timestamp),
      (406, 123, 'La Sabanita', 1, 1, current_timestamp, current_timestamp),
      (407, 123, 'Panapana', 1, 1, current_timestamp, current_timestamp),
      (408, 129, 'Padre Pedro Chien', 1, 1, current_timestamp, current_timestamp),
      (409, 129, 'Río Grande', 1, 1, current_timestamp, current_timestamp),
      (410, 124, 'Andrés Eloy Blanco', 1, 1, current_timestamp, current_timestamp),
      (411, 124, 'Pedro Cova', 1, 1, current_timestamp, current_timestamp),
      (412, 125, 'Raúl Leoni', 1, 1, current_timestamp, current_timestamp),
      (413, 125, 'Barceloneta', 1, 1, current_timestamp, current_timestamp),
      (414, 125, 'Santa Bárbara', 1, 1, current_timestamp, current_timestamp),
      (415, 125, 'San Francisco', 1, 1, current_timestamp, current_timestamp),
      (416, 126, 'Roscio', 1, 1, current_timestamp, current_timestamp),
      (417, 126, 'Salóm', 1, 1, current_timestamp, current_timestamp),
      (418, 127, 'Sifontes', 1, 1, current_timestamp, current_timestamp),
      (419, 127, 'Dalla Costa', 1, 1, current_timestamp, current_timestamp),
      (420, 127, 'San Isidro ', 1, 1, current_timestamp, current_timestamp),
      (421, 128, 'Sucre', 1, 1, current_timestamp, current_timestamp),
      (422, 128, 'Aripao', 1, 1, current_timestamp, current_timestamp),
      (423, 128, 'Guarataro', 1, 1, current_timestamp, current_timestamp),
      (424, 128, 'Las Majadas', 1, 1, current_timestamp, current_timestamp),
      (425, 128, 'Moitaco ', 1, 1, current_timestamp, current_timestamp),
      (426, 130, 'Cojedes', 1, 1, current_timestamp, current_timestamp),
      (427, 130, 'Juan de Mata Suárez', 1, 1, current_timestamp, current_timestamp),
      (428, 134, 'El Pao', 1, 1, current_timestamp, current_timestamp),
      (429, 131, 'Tinaquillo', 1, 1, current_timestamp, current_timestamp),
      (430, 132, 'El Baúl', 1, 1, current_timestamp, current_timestamp),
      (431, 132, 'Sucre', 1, 1, current_timestamp, current_timestamp),
      (432, 133, 'La Aguadita', 1, 1, current_timestamp, current_timestamp),
      (433, 133, 'Macapo', 1, 1, current_timestamp, current_timestamp),
      (434, 135, 'El Amparo', 1, 1, current_timestamp, current_timestamp),
      (435, 135, 'Libertad de Cojedes', 1, 1, current_timestamp, current_timestamp),
      (436, 136, 'Rómulo Gallegos', 1, 1, current_timestamp, current_timestamp),
      (437, 137, 'San Carlos de Austria', 1, 1, current_timestamp, current_timestamp),
      (438, 137, 'Juan Ángel Bravo', 1, 1, current_timestamp, current_timestamp),
      (439, 137, 'Manuel Manrique', 1, 1, current_timestamp, current_timestamp),
      (440, 138, 'General en Jefe José Laurencio Silva', 1, 1, current_timestamp, current_timestamp),
      (441, 139, 'Curiapo', 1, 1, current_timestamp, current_timestamp),
      (442, 139, 'Almirante Luis Brión', 1, 1, current_timestamp, current_timestamp),
      (443, 139, 'Francisco Aniceto Lugo Boca de Cuyubini', 1, 1, current_timestamp, current_timestamp),
      (444, 139, 'Manuel Renaud', 1, 1, current_timestamp, current_timestamp),
      (445, 139, 'Padre Barral', 1, 1, current_timestamp, current_timestamp),
      (446, 139, 'Santos de Abelgas', 1, 1, current_timestamp, current_timestamp),
      (447, 140, 'Imataca Moruca', 1, 1, current_timestamp, current_timestamp),
      (448, 140, 'Cinco de Julio Piacoa', 1, 1, current_timestamp, current_timestamp),
      (449, 140, 'Juan Bautista Arismendi', 1, 1, current_timestamp, current_timestamp),
      (450, 140, 'Manuel Piar Santa Catalina', 1, 1, current_timestamp, current_timestamp),
      (451, 140, 'Rómulo Gallegos', 1, 1, current_timestamp, current_timestamp),
      (452, 141, 'Pedernales', 1, 1, current_timestamp, current_timestamp),
      (453, 141, 'Luis Beltrán Prieto Figueroa', 1, 1, current_timestamp, current_timestamp),
      (454, 142, 'San José (Delta Amacuro) Hacienda del Medio', 1, 1, current_timestamp, current_timestamp),
      (455, 142, 'José Vidal Marcano Caparal de Guara', 1, 1, current_timestamp, current_timestamp),
      (456, 142, 'Juan Millán Urbanización Leonardo Ruíz Pineda', 1, 1, current_timestamp, current_timestamp),
      (457, 142, 'Leonardo Ruíz Pineda Paloma', 1, 1, current_timestamp, current_timestamp),
      (458, 142, 'Mariscal Antonio José de Sucre Urbanización Delfín Mendoza', 1, 1, current_timestamp, current_timestamp),
      (459, 142, 'Monseñor Argimiro García San Rafael', 1, 1, current_timestamp, current_timestamp),
      (460, 142, 'San Rafael', 1, 1, current_timestamp, current_timestamp),
      (461, 142, 'Virgen del Valle', 1, 1, current_timestamp, current_timestamp),
      (462, 143, 'Capadare', 1, 1, current_timestamp, current_timestamp),
      (463, 143, 'La Pastora', 1, 1, current_timestamp, current_timestamp),
      (464, 143, 'Libertador', 1, 1, current_timestamp, current_timestamp),
      (465, 143, 'San Juan de los Cayos', 1, 1, current_timestamp, current_timestamp),
      (466, 144, 'Aracua', 1, 1, current_timestamp, current_timestamp),
      (467, 144, 'La Peña', 1, 1, current_timestamp, current_timestamp),
      (468, 144, 'San Luis', 1, 1, current_timestamp, current_timestamp),
      (469, 145, 'Bariro', 1, 1, current_timestamp, current_timestamp),
      (470, 145, 'Borojó', 1, 1, current_timestamp, current_timestamp),
      (471, 145, 'Capatárida', 1, 1, current_timestamp, current_timestamp),
      (472, 145, 'Guajiro', 1, 1, current_timestamp, current_timestamp),
      (473, 145, 'Seque', 1, 1, current_timestamp, current_timestamp),
      (474, 145, 'Zazárida', 1, 1, current_timestamp, current_timestamp),
      (475, 145, 'Valle de Eroa', 1, 1, current_timestamp, current_timestamp),
      (476, 146, 'Cacique Manaure', 1, 1, current_timestamp, current_timestamp),
      (477, 147, 'Norte', 1, 1, current_timestamp, current_timestamp),
      (478, 147, 'Carirubana', 1, 1, current_timestamp, current_timestamp),
      (479, 147, 'Santa Ana', 1, 1, current_timestamp, current_timestamp),
      (480, 147, 'Urbana Punta Cardón', 1, 1, current_timestamp, current_timestamp),
      (481, 148, 'La Vela de Coro', 1, 1, current_timestamp, current_timestamp),
      (482, 148, 'Acurigua', 1, 1, current_timestamp, current_timestamp),
      (483, 148, 'Guaibacoa', 1, 1, current_timestamp, current_timestamp),
      (484, 148, 'Las Calderas', 1, 1, current_timestamp, current_timestamp),
      (485, 148, 'Macoruca', 1, 1, current_timestamp, current_timestamp),
      (486, 149, 'Dabajuro', 1, 1, current_timestamp, current_timestamp),
      (487, 150, 'Agua Clara', 1, 1, current_timestamp, current_timestamp),
      (488, 150, 'Avaria', 1, 1, current_timestamp, current_timestamp),
      (489, 150, 'Pedregal', 1, 1, current_timestamp, current_timestamp),
      (490, 150, 'Piedra Grande', 1, 1, current_timestamp, current_timestamp),
      (491, 150, 'Purureche', 1, 1, current_timestamp, current_timestamp),
      (492, 151, 'Adaure', 1, 1, current_timestamp, current_timestamp),
      (493, 151, 'Adícora', 1, 1, current_timestamp, current_timestamp),
      (494, 151, 'Baraived', 1, 1, current_timestamp, current_timestamp),
      (495, 151, 'Buena Vista', 1, 1, current_timestamp, current_timestamp),
      (496, 151, 'Jadacaquiva', 1, 1, current_timestamp, current_timestamp),
      (497, 151, 'El Vínculo', 1, 1, current_timestamp, current_timestamp),
      (498, 151, 'El Hato', 1, 1, current_timestamp, current_timestamp),
      (499, 151, 'Moruy', 1, 1, current_timestamp, current_timestamp),
      (500, 151, 'Pueblo Nuevo', 1, 1, current_timestamp, current_timestamp),
      (501, 152, 'Agua Larga', 1, 1, current_timestamp, current_timestamp),
      (502, 152, 'Churuguara', 1, 1, current_timestamp, current_timestamp),
      (503, 152, 'El Paují', 1, 1, current_timestamp, current_timestamp),
      (504, 152, 'Independencia', 1, 1, current_timestamp, current_timestamp),
      (505, 152, 'Mapararí', 1, 1, current_timestamp, current_timestamp),
      (506, 153, 'Jacura', 1, 1, current_timestamp, current_timestamp),
      (507, 154, 'Los Taques', 1, 1, current_timestamp, current_timestamp),
      (508, 155, 'Mene de Mauroa', 1, 1, current_timestamp, current_timestamp),
      (509, 156, 'Guzmán Guillermo', 1, 1, current_timestamp, current_timestamp),
      (510, 156, 'Mitare ', 1, 1, current_timestamp, current_timestamp),
      (511, 156, 'Río Seco', 1, 1, current_timestamp, current_timestamp),
      (512, 156, 'Sabaneta', 1, 1, current_timestamp, current_timestamp),
      (513, 156, 'Santa Ana', 1, 1, current_timestamp, current_timestamp),
      (514, 157, 'Boca del Tocuyo', 1, 1, current_timestamp, current_timestamp),
      (515, 157, 'Chichiriviche', 1, 1, current_timestamp, current_timestamp),
      (516, 158, 'Palmasola', 1, 1, current_timestamp, current_timestamp),
      (517, 159, 'Cabure', 1, 1, current_timestamp, current_timestamp),
      (518, 159, 'Curimagua', 1, 1, current_timestamp, current_timestamp),
      (519, 160, 'San José de la Costa', 1, 1, current_timestamp, current_timestamp),
      (520, 160, 'Píritu', 1, 1, current_timestamp, current_timestamp),
      (521, 161, 'Capital San Francisco', 1, 1, current_timestamp, current_timestamp),
      (522, 162, 'Tucacas', 1, 1, current_timestamp, current_timestamp),
      (523, 162, 'Boca de Aroa', 1, 1, current_timestamp, current_timestamp),
      (524, 163, 'Sucre', 1, 1, current_timestamp, current_timestamp),
      (525, 164, 'Tocópero', 1, 1, current_timestamp, current_timestamp),
      (526, 165, 'Santa Cruz de Bucaral', 1, 1, current_timestamp, current_timestamp),
      (527, 166, 'Bruzual', 1, 1, current_timestamp, current_timestamp),
      (528, 166, 'Urumaco', 1, 1, current_timestamp, current_timestamp),
      (529, 167, 'Puerto Cumarebo', 1, 1, current_timestamp, current_timestamp),
      (530, 167, 'La Ciénaga', 1, 1, current_timestamp, current_timestamp),
      (531, 167, 'La Soledad', 1, 1, current_timestamp, current_timestamp),
      (532, 167, 'Pueblo Cumarebo', 1, 1, current_timestamp, current_timestamp),
      (533, 167, 'Zazárida', 1, 1, current_timestamp, current_timestamp),
      (534, 168, 'Pio Tamayo', 1, 1, current_timestamp, current_timestamp),
      (535, 168, 'Quebrada Honda de Guache', 1, 1, current_timestamp, current_timestamp),
      (536, 169, 'Freitez', 1, 1, current_timestamp, current_timestamp),
      (537, 169, 'José María Blanco', 1, 1, current_timestamp, current_timestamp),
      (538, 172, 'Anzoátegui', 1, 1, current_timestamp, current_timestamp),
      (539, 172, 'Bolívar', 1, 1, current_timestamp, current_timestamp),
      (540, 172, 'Guárico', 1, 1, current_timestamp, current_timestamp),
      (541, 172, 'Hilario Luna y Luna', 1, 1, current_timestamp, current_timestamp),
      (542, 173, 'Cabudare', 1, 1, current_timestamp, current_timestamp),
      (543, 173, 'Agua Viva', 1, 1, current_timestamp, current_timestamp),
      (544, 172, 'Morán', 1, 1, current_timestamp, current_timestamp),
      (545, 174, 'Buría', 1, 1, current_timestamp, current_timestamp),
      (546, 174, 'Sarare', 1, 1, current_timestamp, current_timestamp),
      (547, 175, 'Altagracia', 1, 1, current_timestamp, current_timestamp),
      (548, 175, 'Lara', 1, 1, current_timestamp, current_timestamp),
      (549, 175, 'Chiquinquira', 1, 1, current_timestamp, current_timestamp),
      (550, 176, 'Siquisique', 1, 1, current_timestamp, current_timestamp),
      (551, 176, 'Moroturo', 1, 1, current_timestamp, current_timestamp),
      (552, 170, 'Barquisimeto', 1, 1, current_timestamp, current_timestamp),
      (553, 171, 'Quibor', 1, 1, current_timestamp, current_timestamp),
      (554, 177, 'Betancourt', 1, 1, current_timestamp, current_timestamp),
      (555, 177, 'Páez', 1, 1, current_timestamp, current_timestamp),
      (556, 177, 'Rómulo Gallegos', 1, 1, current_timestamp, current_timestamp),
      (557, 177, 'Gabriel Picón Gonzále', 1, 1, current_timestamp, current_timestamp),
      (558, 177, 'Héctor Amable Mora', 1, 1, current_timestamp, current_timestamp),
      (559, 178, 'La Azulita', 1, 1, current_timestamp, current_timestamp),
      (560, 179, 'Santa Cruz de Mora', 1, 1, current_timestamp, current_timestamp),
      (561, 179, 'Mesa de Las Palmas', 1, 1, current_timestamp, current_timestamp),
      (562, 180, 'Aricagua', 1, 1, current_timestamp, current_timestamp),
      (563, 181, 'Capurí', 1, 1, current_timestamp, current_timestamp),
      (564, 181, 'Chacantá', 1, 1, current_timestamp, current_timestamp),
      (565, 181, 'Guaimaral', 1, 1, current_timestamp, current_timestamp),
      (566, 181, 'Mucuchachí', 1, 1, current_timestamp, current_timestamp),
      (567, 182, 'Fernández Peña (Ejido)', 1, 1, current_timestamp, current_timestamp),
      (568, 182, 'Acequias', 1, 1, current_timestamp, current_timestamp),
      (569, 182, 'Jají', 1, 1, current_timestamp, current_timestamp),
      (570, 182, 'La Mesa', 1, 1, current_timestamp, current_timestamp),
      (571, 182, 'San José del Sur', 1, 1, current_timestamp, current_timestamp),
      (572, 183, 'Tucaní', 1, 1, current_timestamp, current_timestamp),
      (573, 184, 'Santo Domingo', 1, 1, current_timestamp, current_timestamp),
      (574, 185, 'Guaraque', 1, 1, current_timestamp, current_timestamp),
      (575, 186, 'Arapuey', 1, 1, current_timestamp, current_timestamp),
      (576, 186, 'Palmira', 1, 1, current_timestamp, current_timestamp),
      (577, 187, 'Torondoy', 1, 1, current_timestamp, current_timestamp),
      (578, 188, 'Antonio Spinetti Dini', 1, 1, current_timestamp, current_timestamp),
      (579, 188, 'Arias', 1, 1, current_timestamp, current_timestamp),
      (580, 188, 'Caracciolo Parra Pérez', 1, 1, current_timestamp, current_timestamp),
      (581, 188, 'Domingo Peña ', 1, 1, current_timestamp, current_timestamp),
      (582, 188, 'El Llano', 1, 1, current_timestamp, current_timestamp),
      (583, 188, 'Gonzalo Picón Febres', 1, 1, current_timestamp, current_timestamp),
      (584, 188, 'Jacinto Plaza', 1, 1, current_timestamp, current_timestamp),
      (585, 188, 'Juan Rodríguez Suárez', 1, 1, current_timestamp, current_timestamp),
      (586, 188, 'Lasso de la Vega', 1, 1, current_timestamp, current_timestamp),
      (587, 188, 'Mariano Picón Sala', 1, 1, current_timestamp, current_timestamp),
      (588, 188, 'Milla', 1, 1, current_timestamp, current_timestamp),
      (589, 188, 'Osuna Rodríguez', 1, 1, current_timestamp, current_timestamp),
      (590, 188, 'Sagrario', 1, 1, current_timestamp, current_timestamp),
      (591, 188, 'El Morro', 1, 1, current_timestamp, current_timestamp),
      (592, 188, 'Los Nevados', 1, 1, current_timestamp, current_timestamp),
      (593, 189, 'Andrés Eloy Blanco', 1, 1, current_timestamp, current_timestamp),
      (594, 189, 'La Venta', 1, 1, current_timestamp, current_timestamp),
      (595, 189, 'Piñango', 1, 1, current_timestamp, current_timestamp),
      (596, 189, 'Timotes', 1, 1, current_timestamp, current_timestamp),
      (597, 190, 'Eloy Paredes', 1, 1, current_timestamp, current_timestamp),
      (598, 190, 'San Rafael de Alcázar', 1, 1, current_timestamp, current_timestamp),
      (599, 191, 'Santa María de Caparo', 1, 1, current_timestamp, current_timestamp),
      (600, 192, 'Pueblo Llano', 1, 1, current_timestamp, current_timestamp),
      (601, 193, 'Cacute', 1, 1, current_timestamp, current_timestamp),
      (602, 193, 'Mucuchíes', 1, 1, current_timestamp, current_timestamp),
      (603, 194, 'Gerónimo Maldonado', 1, 1, current_timestamp, current_timestamp),
      (604, 194, 'Bailadores', 1, 1, current_timestamp, current_timestamp),
      (605, 195, 'Tabay', 1, 1, current_timestamp, current_timestamp),
      (606, 196, 'Chiguará', 1, 1, current_timestamp, current_timestamp),
      (607, 196, 'Estánquez', 1, 1, current_timestamp, current_timestamp),
      (608, 196, 'Lagunillas', 1, 1, current_timestamp, current_timestamp),
      (609, 196, 'Pueblo Nuevo del Sur', 1, 1, current_timestamp, current_timestamp),
      (610, 196, 'San Juan', 1, 1, current_timestamp, current_timestamp),
      (611, 197, 'El Amparo', 1, 1, current_timestamp, current_timestamp),
      (612, 197, 'El Llano', 1, 1, current_timestamp, current_timestamp),
      (613, 197, 'San Francisco', 1, 1, current_timestamp, current_timestamp),
      (614, 197, 'Tovar', 1, 1, current_timestamp, current_timestamp),
      (615, 198, 'Independencia', 1, 1, current_timestamp, current_timestamp),
      (616, 198, 'María de la Concepción Palacios Blanco', 1, 1, current_timestamp, current_timestamp),
      (617, 198, 'Nueva Bolivia', 1, 1, current_timestamp, current_timestamp),
      (618, 198, 'Santa Apolonia', 1, 1, current_timestamp, current_timestamp),
      (619, 199, 'Caño El Tigre', 1, 1, current_timestamp, current_timestamp),
      (620, 199, 'Zea', 1, 1, current_timestamp, current_timestamp),
      (621, 200, 'San Antonio de Maturín', 1, 1, current_timestamp, current_timestamp),
      (622, 200, 'San Francisco de Maturín', 1, 1, current_timestamp, current_timestamp),
      (623, 201, 'Aguasay', 1, 1, current_timestamp, current_timestamp),
      (624, 202, 'Caripito', 1, 1, current_timestamp, current_timestamp),
      (625, 203, 'El Guácharo', 1, 1, current_timestamp, current_timestamp),
      (626, 203, 'Caripe', 1, 1, current_timestamp, current_timestamp),
      (627, 204, 'Capital Cedeño', 1, 1, current_timestamp, current_timestamp),
      (628, 204, 'San Félix de Cantalicio', 1, 1, current_timestamp, current_timestamp),
      (629, 205, 'El Tejero', 1, 1, current_timestamp, current_timestamp),
      (630, 205, 'Punta de Mata', 1, 1, current_timestamp, current_timestamp),
      (631, 206, 'Chaguaramas', 1, 1, current_timestamp, current_timestamp),
      (632, 206, 'Temblador', 1, 1, current_timestamp, current_timestamp),
      (633, 207, 'Alto de los Godos', 1, 1, current_timestamp, current_timestamp),
      (634, 207, 'Boquerón', 1, 1, current_timestamp, current_timestamp),
      (635, 207, 'Las Cocuizas', 1, 1, current_timestamp, current_timestamp),
      (636, 207, 'La Cruz', 1, 1, current_timestamp, current_timestamp),
      (637, 207, 'San Simón', 1, 1, current_timestamp, current_timestamp),
      (638, 207, 'El Corozo', 1, 1, current_timestamp, current_timestamp),
      (639, 207, 'El Furrial', 1, 1, current_timestamp, current_timestamp),
      (640, 207, 'Jusepín', 1, 1, current_timestamp, current_timestamp),
      (641, 207, 'La Pica', 1, 1, current_timestamp, current_timestamp),
      (642, 207, 'San Vicente', 1, 1, current_timestamp, current_timestamp),
      (643, 208, 'Aparicio', 1, 1, current_timestamp, current_timestamp),
      (644, 208, 'Chaguamal', 1, 1, current_timestamp, current_timestamp),
      (645, 208, 'El Pinto', 1, 1, current_timestamp, current_timestamp),
      (646, 208, 'Guanaguana', 1, 1, current_timestamp, current_timestamp),
      (647, 208, 'La Toscana', 1, 1, current_timestamp, current_timestamp),
      (648, 209, 'Cachipo', 1, 1, current_timestamp, current_timestamp),
      (649, 209, 'Quiriquire', 1, 1, current_timestamp, current_timestamp),
      (650, 210, 'Santa Bárbara', 1, 1, current_timestamp, current_timestamp),
      (651, 211, 'Barrancas', 1, 1, current_timestamp, current_timestamp),
      (652, 212, 'Uracoa', 1, 1, current_timestamp, current_timestamp),
      (653, 213, 'Antolín del Campo', 1, 1, current_timestamp, current_timestamp),
      (654, 214, 'Arismendi', 1, 1, current_timestamp, current_timestamp),
      (655, 215, 'San Juan Bautista', 1, 1, current_timestamp, current_timestamp),
      (656, 215, 'Zabala', 1, 1, current_timestamp, current_timestamp),
      (657, 216, 'García', 1, 1, current_timestamp, current_timestamp),
      (658, 216, 'Francisco Fajardo', 1, 1, current_timestamp, current_timestamp),
      (659, 217, 'Bolívar', 1, 1, current_timestamp, current_timestamp),
      (660, 217, 'Guevara', 1, 1, current_timestamp, current_timestamp),
      (661, 217, 'Cerro de Matasiete', 1, 1, current_timestamp, current_timestamp),
      (662, 217, 'Santa Ana', 1, 1, current_timestamp, current_timestamp),
      (663, 217, 'Sucre', 1, 1, current_timestamp, current_timestamp),
      (664, 218, 'Aguirre', 1, 1, current_timestamp, current_timestamp),
      (665, 218, 'Maneiro', 1, 1, current_timestamp, current_timestamp),
      (666, 219, 'Adrián', 1, 1, current_timestamp, current_timestamp),
      (667, 219, 'Juan Griego', 1, 1, current_timestamp, current_timestamp),
      (668, 219, 'Yaguaraparo', 1, 1, current_timestamp, current_timestamp),
      (669, 220, 'Porlamar', 1, 1, current_timestamp, current_timestamp),
      (670, 221, 'San Francisco de Macanao', 1, 1, current_timestamp, current_timestamp),
      (671, 221, 'Boca de Río', 1, 1, current_timestamp, current_timestamp),
      (672, 222, 'Tubores', 1, 1, current_timestamp, current_timestamp),
      (673, 223, 'Villalba', 1, 1, current_timestamp, current_timestamp),
      (674, 224, 'Agua Blanca', 1, 1, current_timestamp, current_timestamp),
      (675, 225, 'Araure', 1, 1, current_timestamp, current_timestamp),
      (676, 226, 'Píritu', 1, 1, current_timestamp, current_timestamp),
      (677, 226, 'Uveral', 1, 1, current_timestamp, current_timestamp),
      (678, 227, 'Guanare', 1, 1, current_timestamp, current_timestamp),
      (679, 228, 'Guanarito', 1, 1, current_timestamp, current_timestamp),
      (680, 229, 'Peña Blanca', 1, 1, current_timestamp, current_timestamp),
      (681, 230, 'Aparición', 1, 1, current_timestamp, current_timestamp),
      (682, 230, 'Ospino', 1, 1, current_timestamp, current_timestamp),
      (683, 231, 'Acarigua', 1, 1, current_timestamp, current_timestamp),
      (684, 231, 'Payara', 1, 1, current_timestamp, current_timestamp),
      (685, 232, 'Papelón', 1, 1, current_timestamp, current_timestamp),
      (686, 233, 'Boconoíto', 1, 1, current_timestamp, current_timestamp),
      (687, 234, 'San Rafael de Onoto', 1, 1, current_timestamp, current_timestamp),
      (688, 234, 'Santa Fé', 1, 1, current_timestamp, current_timestamp),
      (689, 235, 'Florida', 1, 1, current_timestamp, current_timestamp),
      (690, 235, 'El Playón', 1, 1, current_timestamp, current_timestamp),
      (691, 236, 'Biscucuy', 1, 1, current_timestamp, current_timestamp),
      (692, 236, 'Concepción', 1, 1, current_timestamp, current_timestamp),
      (693, 236, 'San José de Saguaz', 1, 1, current_timestamp, current_timestamp),
      (694, 236, 'San Rafael de Palo Alzado', 1, 1, current_timestamp, current_timestamp),
      (695, 236, 'Uvencio Antonio Velásquez', 1, 1, current_timestamp, current_timestamp),
      (696, 236, 'Villa Rosa', 1, 1, current_timestamp, current_timestamp),
      (697, 237, 'Canelones', 1, 1, current_timestamp, current_timestamp),
      (698, 237, 'Santa Cruz', 1, 1, current_timestamp, current_timestamp),
      (699, 237, 'San Isidro Labrador', 1, 1, current_timestamp, current_timestamp),
      (700, 238, 'Mariño', 1, 1, current_timestamp, current_timestamp),
      (701, 238, 'Rómulo Gallegos', 1, 1, current_timestamp, current_timestamp),
      (702, 239, 'San José de Aerocuar', 1, 1, current_timestamp, current_timestamp),
      (703, 239, 'Tavera Acosta', 1, 1, current_timestamp, current_timestamp),
      (704, 240, 'Río Caribe', 1, 1, current_timestamp, current_timestamp),
      (705, 240, 'Antonio José de Sucre', 1, 1, current_timestamp, current_timestamp),
      (706, 240, 'El Morro de Puerto Santo', 1, 1, current_timestamp, current_timestamp),
      (707, 240, 'Puerto Santo', 1, 1, current_timestamp, current_timestamp),
      (708, 240, 'San Juan de las Galdonas', 1, 1, current_timestamp, current_timestamp),
      (709, 241, 'El Pilar', 1, 1, current_timestamp, current_timestamp),
      (710, 241, 'El Rincón', 1, 1, current_timestamp, current_timestamp),
      (711, 241, 'General Francisco Antonio Váquez', 1, 1, current_timestamp, current_timestamp),
      (712, 241, 'Guaraúnos', 1, 1, current_timestamp, current_timestamp),
      (713, 241, 'Tunapuicito', 1, 1, current_timestamp, current_timestamp),
      (714, 241, 'Unión', 1, 1, current_timestamp, current_timestamp),
      (715, 242, 'Santa Catalina', 1, 1, current_timestamp, current_timestamp),
      (716, 242, 'Santa Rosa', 1, 1, current_timestamp, current_timestamp),
      (717, 242, 'Santa Teresa', 1, 1, current_timestamp, current_timestamp),
      (718, 242, 'Bolívar', 1, 1, current_timestamp, current_timestamp),
      (719, 242, 'Maracapana', 1, 1, current_timestamp, current_timestamp),
      (720, 243, 'Bolívar', 1, 1, current_timestamp, current_timestamp),
      (721, 244, 'El Paujil', 1, 1, current_timestamp, current_timestamp),
      (722, 245, 'Cruz Salmerón Acosta', 1, 1, current_timestamp, current_timestamp),
      (723, 245, 'Manicuare', 1, 1, current_timestamp, current_timestamp),
      (724, 246, 'Tunapuy', 1, 1, current_timestamp, current_timestamp),
      (725, 246, 'Campo Elías', 1, 1, current_timestamp, current_timestamp),
      (726, 247, 'Irapa', 1, 1, current_timestamp, current_timestamp),
      (727, 247, 'Campo Claro', 1, 1, current_timestamp, current_timestamp),
      (728, 247, 'Maraval', 1, 1, current_timestamp, current_timestamp),
      (729, 247, 'Soro', 1, 1, current_timestamp, current_timestamp),
      (730, 248, 'Mejía', 1, 1, current_timestamp, current_timestamp),
      (731, 249, 'Cumanacoa', 1, 1, current_timestamp, current_timestamp),
      (732, 249, 'Aricagua', 1, 1, current_timestamp, current_timestamp),
      (733, 249, 'San Fernando', 1, 1, current_timestamp, current_timestamp),
      (734, 249, 'San Lorenzo', 1, 1, current_timestamp, current_timestamp),
      (735, 250, 'Villa Frontado', 1, 1, current_timestamp, current_timestamp),
      (736, 250, 'Catuaro', 1, 1, current_timestamp, current_timestamp),
      (737, 250, 'Rendón', 1, 1, current_timestamp, current_timestamp),
      (738, 250, 'San Cruz', 1, 1, current_timestamp, current_timestamp),
      (739, 250, 'Santa María', 1, 1, current_timestamp, current_timestamp),
      (740, 251, 'Altagracia', 1, 1, current_timestamp, current_timestamp),
      (741, 251, 'Santa Inés', 1, 1, current_timestamp, current_timestamp),
      (742, 251, 'Valentín Valiente', 1, 1, current_timestamp, current_timestamp),
      (743, 251, 'Ayacucho', 1, 1, current_timestamp, current_timestamp),
      (744, 251, 'San Juan', 1, 1, current_timestamp, current_timestamp),
      (745, 251, 'Raúl Leoni', 1, 1, current_timestamp, current_timestamp),
      (746, 251, 'Gran Mariscal', 1, 1, current_timestamp, current_timestamp),
      (747, 252, 'Cristóbal Colón', 1, 1, current_timestamp, current_timestamp),
      (748, 252, 'Bideau', 1, 1, current_timestamp, current_timestamp),
      (749, 252, 'Punta de Piedras', 1, 1, current_timestamp, current_timestamp),
      (750, 252, 'Güiria', 1, 1, current_timestamp, current_timestamp),
      (751, 253, 'Andrés Bello', 1, 1, current_timestamp, current_timestamp),
      (752, 254, 'Antonio Rómulo Costa', 1, 1, current_timestamp, current_timestamp),
      (753, 255, 'Ayacucho', 1, 1, current_timestamp, current_timestamp),
      (754, 255, 'San Pedro del Río', 1, 1, current_timestamp, current_timestamp),
      (755, 256, 'Bolívar', 1, 1, current_timestamp, current_timestamp),
      (756, 257, 'Cárdenas', 1, 1, current_timestamp, current_timestamp),
      (757, 258, 'Córdoba', 1, 1, current_timestamp, current_timestamp),
      (758, 259, 'Fernández Feo', 1, 1, current_timestamp, current_timestamp),
      (759, 259, 'Alberto Adriani', 1, 1, current_timestamp, current_timestamp),
      (760, 260, 'Francisco de Miranda', 1, 1, current_timestamp, current_timestamp),
      (761, 261, 'García de Hevia', 1, 1, current_timestamp, current_timestamp),
      (762, 261, 'Boca de Grita', 1, 1, current_timestamp, current_timestamp),
      (763, 262, 'Guásimos', 1, 1, current_timestamp, current_timestamp),
      (764, 263, 'Independencia', 1, 1, current_timestamp, current_timestamp),
      (765, 262, 'Juan Germán Roscio', 1, 1, current_timestamp, current_timestamp),
      (766, 264, 'Jáuregui', 1, 1, current_timestamp, current_timestamp),
      (767, 265, 'José María Vargas', 1, 1, current_timestamp, current_timestamp),
      (768, 266, 'Junín', 1, 1, current_timestamp, current_timestamp),
      (769, 266, 'La Petrólea', 1, 1, current_timestamp, current_timestamp),
      (770, 267, 'Libertad', 1, 1, current_timestamp, current_timestamp),
      (771, 268, 'Capital Libertador', 1, 1, current_timestamp, current_timestamp),
      (772, 269, 'Lobatera', 1, 1, current_timestamp, current_timestamp),
      (773, 270, 'Michelena', 1, 1, current_timestamp, current_timestamp),
      (774, 271, 'Panamericano', 1, 1, current_timestamp, current_timestamp),
      (775, 272, 'Pedro María Ureña', 1, 1, current_timestamp, current_timestamp),
      (776, 273, 'Delicias', 1, 1, current_timestamp, current_timestamp),
      (777, 274, 'Samuel Darío Maldonado', 1, 1, current_timestamp, current_timestamp),
      (778, 274, 'Boconó', 1, 1, current_timestamp, current_timestamp),
      (779, 275, 'La Concordia', 1, 1, current_timestamp, current_timestamp),
      (780, 275, 'San Juan Bautista', 1, 1, current_timestamp, current_timestamp),
      (781, 275, 'Pedro María Morantes', 1, 1, current_timestamp, current_timestamp),
      (782, 276, 'Seboruco', 1, 1, current_timestamp, current_timestamp),
      (783, 277, 'Simón Rodríguez', 1, 1, current_timestamp, current_timestamp),
      (784, 278, 'Sucre', 1, 1, current_timestamp, current_timestamp),
      (785, 279, 'San José', 1, 1, current_timestamp, current_timestamp),
      (786, 280, 'Uribante', 1, 1, current_timestamp, current_timestamp),
      (787, 280, 'Juan Pablo Peñalosa', 1, 1, current_timestamp, current_timestamp),
      (788, 280, 'Potosí', 1, 1, current_timestamp, current_timestamp),
      (789, 281, 'San Judas Tadeo', 1, 1, current_timestamp, current_timestamp),
      (800, 282, 'Araguaney', 1, 1, current_timestamp, current_timestamp),
      (801, 282, 'El Jaguito', 1, 1, current_timestamp, current_timestamp),
      (802, 283, 'Boconó', 1, 1, current_timestamp, current_timestamp),
      (803, 284, 'Sabana Grande', 1, 1, current_timestamp, current_timestamp),
      (804, 284, 'Cheregüé', 1, 1, current_timestamp, current_timestamp),
      (805, 285, 'Arnoldo Gabaldón', 1, 1, current_timestamp, current_timestamp),
      (806, 285, 'Bolivia', 1, 1, current_timestamp, current_timestamp),
      (807, 285, 'Carrillo', 1, 1, current_timestamp, current_timestamp),
      (808, 285, 'Manuel Salvador Ulloa', 1, 1, current_timestamp, current_timestamp),
      (809, 286, 'Carache', 1, 1, current_timestamp, current_timestamp),
      (810, 286, 'La Concepción', 1, 1, current_timestamp, current_timestamp),
      (811, 286, 'Santa Cruz', 1, 1, current_timestamp, current_timestamp),
      (812, 287, 'Escuque', 1, 1, current_timestamp, current_timestamp),
      (813, 287, 'Santa Rita', 1, 1, current_timestamp, current_timestamp),
      (814, 288, 'El Socorro', 1, 1, current_timestamp, current_timestamp),
      (815, 288, 'Antonio José de Sucre', 1, 1, current_timestamp, current_timestamp),
      (816, 289, 'Campo Elías', 1, 1, current_timestamp, current_timestamp),
      (817, 289, 'Arnoldo Gabaldón', 1, 1, current_timestamp, current_timestamp),
      (818, 290, 'Santa Apolonia', 1, 1, current_timestamp, current_timestamp),
      (819, 290, 'La Ceiba', 1, 1, current_timestamp, current_timestamp),
      (820, 291, 'Agua Santa', 1, 1, current_timestamp, current_timestamp),
      (821, 291, 'Valerita', 1, 1, current_timestamp, current_timestamp),
      (822, 292, 'Carmelo', 1, 1, current_timestamp, current_timestamp),
      (823, 292, 'Santa María del Horcón', 1, 1, current_timestamp, current_timestamp),
      (824, 293, 'Motatán', 1, 1, current_timestamp, current_timestamp),
      (825, 293, 'Jalisco', 1, 1, current_timestamp, current_timestamp),
      (826, 294, 'Pampán', 1, 1, current_timestamp, current_timestamp),
      (827, 294, 'Santa Ana', 1, 1, current_timestamp, current_timestamp),
      (828, 295, 'Pampanito', 1, 1, current_timestamp, current_timestamp),
      (829, 295, 'Pampanito II', 1, 1, current_timestamp, current_timestamp),
      (830, 296, 'Betijoque', 1, 1, current_timestamp, current_timestamp),
      (831, 296, 'José Gregorio Hernández', 1, 1, current_timestamp, current_timestamp),
      (832, 296, 'La Pueblita', 1, 1, current_timestamp, current_timestamp),
      (833, 297, 'Carvajal', 1, 1, current_timestamp, current_timestamp),
      (834, 297, 'Campo Alegre', 1, 1, current_timestamp, current_timestamp),
      (835, 297, 'Antonio Nicolás Briceño', 1, 1, current_timestamp, current_timestamp),
      (836, 298, 'Sabana de Mendoza', 1, 1, current_timestamp, current_timestamp),
      (837, 298, 'Junín', 1, 1, current_timestamp, current_timestamp),
      (838, 298, 'Valmore Rodríguez', 1, 1, current_timestamp, current_timestamp),
      (839, 298, 'El Paraíso', 1, 1, current_timestamp, current_timestamp),
      (840, 299, 'Andrés Linares', 1, 1, current_timestamp, current_timestamp),
      (841, 299, 'Cristóbal Mendoza', 1, 1, current_timestamp, current_timestamp),
      (842, 299, 'Carrillo', 1, 1, current_timestamp, current_timestamp),
      (843, 300, 'Cabimbú', 1, 1, current_timestamp, current_timestamp),
      (844, 300, 'Jajó', 1, 1, current_timestamp, current_timestamp),
      (845, 300, 'La Mesa de Esnujaque', 1, 1, current_timestamp, current_timestamp),
      (846, 300, 'Santiago', 1, 1, current_timestamp, current_timestamp),
      (847, 300, 'La Quebrada', 1, 1, current_timestamp, current_timestamp),
      (848, 301, 'Juan Ignacio Montilla', 1, 1, current_timestamp, current_timestamp),
      (849, 301, 'La Beatriz', 1, 1, current_timestamp, current_timestamp),
      (850, 301, 'La Puerta', 1, 1, current_timestamp, current_timestamp),
      (851, 301, 'Mendoza del Valle de Momboy', 1, 1, current_timestamp, current_timestamp),
      (852, 301, 'Mercedes Díaz', 1, 1, current_timestamp, current_timestamp),
      (853, 301, 'San Luis', 1, 1, current_timestamp, current_timestamp),
      (854, 302, 'El Guayabo', 1, 1, current_timestamp, current_timestamp),
      (855, 302, 'Farriar', 1, 1, current_timestamp, current_timestamp),
      (856, 303, 'Arístides Bastidas', 1, 1, current_timestamp, current_timestamp),
      (857, 304, 'Bolívar', 1, 1, current_timestamp, current_timestamp),
      (858, 305, 'Chivacoa', 1, 1, current_timestamp, current_timestamp),
      (859, 305, 'Campo Elías', 1, 1, current_timestamp, current_timestamp),
      (860, 306, 'Cocorote', 1, 1, current_timestamp, current_timestamp),
      (861, 307, 'Independencia', 1, 1, current_timestamp, current_timestamp),
      (862, 308, 'José Antonio Páez', 1, 1, current_timestamp, current_timestamp),
      (863, 309, 'La Trinidad', 1, 1, current_timestamp, current_timestamp),
      (864, 310, 'Manuel Monge', 1, 1, current_timestamp, current_timestamp),
      (865, 311, 'Salóm', 1, 1, current_timestamp, current_timestamp),
      (866, 311, 'Nirgua', 1, 1, current_timestamp, current_timestamp),
      (867, 312, 'San Andrés', 1, 1, current_timestamp, current_timestamp),
      (868, 312, 'Yaritagua', 1, 1, current_timestamp, current_timestamp),
      (869, 313, 'San Felipe', 1, 1, current_timestamp, current_timestamp),
      (870, 313, 'San Javier', 1, 1, current_timestamp, current_timestamp),
      (871, 314, 'Sucre', 1, 1, current_timestamp, current_timestamp),
      (872, 315, 'Urachiche', 1, 1, current_timestamp, current_timestamp),
      (873, 316, 'Isla de Toas', 1, 1, current_timestamp, current_timestamp),
      (874, 316, 'Monagas', 1, 1, current_timestamp, current_timestamp),
      (875, 317, 'San Timoteo', 1, 1, current_timestamp, current_timestamp),
      (876, 317, 'Libertador', 1, 1, current_timestamp, current_timestamp),
      (877, 317, 'Pueblo Nuevo', 1, 1, current_timestamp, current_timestamp),
      (878, 318, 'La Rosa', 1, 1, current_timestamp, current_timestamp),
      (879, 318, 'Rómulo Betancourt', 1, 1, current_timestamp, current_timestamp),
      (880, 318, 'San Benito', 1, 1, current_timestamp, current_timestamp),
      (881, 318, 'Arístides Calvani', 1, 1, current_timestamp, current_timestamp),
      (882, 319, 'Encontrados', 1, 1, current_timestamp, current_timestamp),
      (883, 320, 'Moralito', 1, 1, current_timestamp, current_timestamp),
      (884, 320, 'San Carlos del Zulia', 1, 1, current_timestamp, current_timestamp),
      (885, 320, 'Santa Cruz del Zulia', 1, 1, current_timestamp, current_timestamp),
      (886, 320, 'Santa Bárbara', 1, 1, current_timestamp, current_timestamp),
      (887, 320, 'Urribarrí', 1, 1, current_timestamp, current_timestamp),
      (888, 321, 'Carlos Quevedo', 1, 1, current_timestamp, current_timestamp),
      (889, 321, 'Francisco Javier Pulgar', 1, 1, current_timestamp, current_timestamp),
      (890, 322, 'La Concepción', 1, 1, current_timestamp, current_timestamp),
      (891, 322, 'Mariano Parra León', 1, 1, current_timestamp, current_timestamp),
      (892, 323, 'Concepción', 1, 1, current_timestamp, current_timestamp),
      (893, 323, 'Chiquinquirá', 1, 1, current_timestamp, current_timestamp),
      (894, 323, 'Potreritos', 1, 1, current_timestamp, current_timestamp),
      (895, 324, 'Libertad', 1, 1, current_timestamp, current_timestamp),
      (896, 324, 'Venezuela', 1, 1, current_timestamp, current_timestamp),
      (897, 324, 'Campo Lara', 1, 1, current_timestamp, current_timestamp),
      (898, 325, 'San José de Perijá', 1, 1, current_timestamp, current_timestamp),
      (899, 326, 'mara', 1, 1, current_timestamp, current_timestamp),
      (900, 327, 'Bolívar', 1, 1, current_timestamp, current_timestamp),
      (901, 327, 'Coquivacoa', 1, 1, current_timestamp, current_timestamp),
      (902, 327, 'Chiquinquirá', 1, 1, current_timestamp, current_timestamp),
      (903, 327, 'Raúl Leoni', 1, 1, current_timestamp, current_timestamp),
      (904, 327, 'Santa Lucía', 1, 1, current_timestamp, current_timestamp),
      (905, 327, 'San Isidro', 1, 1, current_timestamp, current_timestamp),
      (906, 328, 'Altagracia', 1, 1, current_timestamp, current_timestamp),
      (907, 328, 'Faría', 1, 1, current_timestamp, current_timestamp),
      (908, 328, 'San Antonio', 1, 1, current_timestamp, current_timestamp),
      (909, 328, 'San José', 1, 1, current_timestamp, current_timestamp),
      (910, 329, 'Guajira', 1, 1, current_timestamp, current_timestamp),
      (911, 329, 'Elías Sánchez Rubio', 1, 1, current_timestamp, current_timestamp),
      (912, 330, 'El Rosario', 1, 1, current_timestamp, current_timestamp),
      (913, 331, 'San Francisco', 1, 1, current_timestamp, current_timestamp),
      (914, 331, 'Los Cortijos', 1, 1, current_timestamp, current_timestamp),
      (915, 332, 'Santa Rita', 1, 1, current_timestamp, current_timestamp),
      (916, 332, 'Urribarrí', 1, 1, current_timestamp, current_timestamp),
      (917, 333, 'Rafael', 1, 1, current_timestamp, current_timestamp),
      (918, 333, 'Manuel Manrique', 1, 1, current_timestamp, current_timestamp),
      (919, 334, 'Gibraltar', 1, 1, current_timestamp, current_timestamp),
      (920, 334, 'Rómulo Gallegos', 1, 1, current_timestamp, current_timestamp),
      (921, 335, 'Rafael Urdaneta ', 1, 1, current_timestamp, current_timestamp),
      (922, 334, 'La Victoria', 1, 1, current_timestamp, current_timestamp),
      (923, 335, 'Raúl Cuenca', 1, 1, current_timestamp, current_timestamp),
      (924, 336, 'Jesús María Semprún', 1, 1, current_timestamp, current_timestamp);");
  }

}
